name = "ClipData"
uuid = "39db22c5-8506-4ef9-b8dc-9d8ef5f2b71d"
authors = ["Peter Deffebach <p.deffebach@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Tables = "1.4"
CSV = "0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
